services:
  frontend:
    image: cilent_prod
    container_name: cilent_prod
    build:
      context: ./frontend
      target: prod
    networks:
      ktc_net:
        ipv4_address: 192.168.200.5
  backend:
    image: server_prod
    container_name: server_prod
    build:
      context: ./backend
      target: prod
    env_file:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    networks:
      ktc_net:
        ipv4_address: 192.168.200.4
