services:
  frontend:
    networks:
      ktc_net:
        ipv4_address: 192.168.200.5
  backend:
    networks:
      ktc_net:
        ipv4_address: 192.168.200.4
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      ktc_net:
        ipv4_address: 192.168.200.2

volumes:
  postgres_data:

networks:
  ktc_net:
    ipam:
      driver: default
      config:
        - subnet: '192.168.200.0/24'
          gateway: 192.168.200.1
