services:
  frontend:
    image: client_dev
    container_name: client_dev
    build:
      context: ./frontend
      target: dev
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: app/client
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/.env.development
    ports:
      - '5173:5173'
    env_file:
      - './frontend/.env.development'
  backend:
    image: server_dev
    container_name: server_dev
    build:
      context: ./backend
      target: dev
    develop:
      watch:
        - action: sync
          path: ./backend
          target: app/server
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./.env.dev
    ports:
      - '3000:3000'
    env_file:
      - './.env.dev'
  db:
    environment:
      - POSTGRES_HOST=192.168.200.2
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ktc
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    networks:
      ktc_net:
        ipv4_address: 192.168.200.3

volumes:
  pgadmin_data:
