services:
  frontend:
    image: cilent_prod
    container_name: cilent_prod
    build:
      context: ./frontend
      target: prod
    expose:
      - '5173'
    env_file:
      - './frontend/.env.production'
  backend:
    image: server_prod
    container_name: server_prod
    build:
      context: ./backend
      target: prod
    expose:
      - '3000'
    env_file:
      - '.env.prod'
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - ktc_net
