services:
  frontend:
    image: cilent_prod
    container_name: cilent_prod
    build:
      context: ./frontend
      target: prod
    expose:
      - '5173'
    env_file:
      - './frontend/.env.production'
  backend:
    image: server_prod
    container_name: server_prod
    build:
      context: ./backend
      target: prod
    expose:
      - '3000'
    env_file:
      - './backend/.env.prod'
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /usr/lib/ssl/selfsigned/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro
      - /usr/lib/ssl/selfsigned/selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - ktc_net
