services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_DB: ktc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      ktc_net:
        ipv4_address: 192.168.200.2

volumes:
  postgres_data:

networks:
  ktc_net:
    ipam:
      driver: default
      config:
        - subnet: '192.168.200.0/24'
          gateway: 192.168.200.1
